### PR TITLE
Remove null coalescing operator as it is redundant.

### PR DESCRIPTION
**Pull request by WojcikMike**
fixes: https://github.com/Particular/dotnetTemplates/issues/20

### CODE REVIEW

**Comment by bording** [comment]
I believe the same logic applies for the code in the ScAdapterService template as well, so that should be included.

**Comment by timbussmann** [comment]
LGTM but should this target `develop` instead?

**Comment by WojcikMike** [comment]
Changed the target now rebasing

**Comment by WojcikMike** [comment]
And rebased

**Comment by bording** [comment]
What's the release plan for this? Having this against develop implies a new minor.

**Comment by timbussmann** [comment]
> To be honest, I'm even sure this change warrants a new release at all.

that's why I wasn't aiming for a patch release in the first place. I think we can hold this a little bit until there is something which is going to be released?

**Comment by WojcikMike** [comment]
I agree with that. Overall it is an aesthetic change to the code base without a change in behavior.

**Pull request merged**
