### PR TITLE
Fix broken dependabot package updates due to Nuget version range matching

### PR DESCRIPTION
**Pull request by ramonsmits**

### CODE REVIEW

**Comment by mauroservienti** [comment]
Doesn't removing an explicit reference to Core make it so that NuGet brings in the lowest minor?

**Comment by ramonsmits** [comment]
> Doesn't removing an explicit reference to Core make it so that NuGet brings in the lowest minor?

@mauroservienti yes, but adding it results in dependabot wanting to release the latest rc version of Core unless I ask dependabot to ignore the major

**Comment by mauroservienti** [comment]
We could also ignore a specific version, not necessarily the major.

**Comment by bording** [comment]
@ramonsmits I don't think we should make this change. For templates, we should be wanting to have an NServiceBus reference.

It's not clear to me what problem you're trying to solve, but I think we need to find another way to do it.

**Pull request closed without merging**
